# Site settings
title: 往事如煙 | 我的故事
description: '往事回憶，意味著什麼？是漸漸老去？還是行將就木？'
keywords: '往事回憶'
url: 'https://je-pense.github.io/wangshiruyan'
author:
  name: '阿甘'
  email: 'winwinsfu@gmail.com'
  url: 'https://je-pense.github.io/'

# Build settings
baseurl: /wangshiruyan # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: '1.0'

# Options
custom_header: false
custom_nav_footer: false
reverse: false
